# Site settings

timezone: nil

title: 踏雪无痕d博客 # Title of your site
email: hun333@126.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  走你认定了的路吧，不要耽搁了自己的行程
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://agenthun.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     example  # Replace this with your Twitter username
github_username:      agenthun  # Replace this with your GitHub username
linkedin_username:    example  # Replace this with your LinkedIn username
google_plus_username: example  # Replace this with your Google+ username
facebook_username:    example  # Replace this with your Facebook username
dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
