# Site settings
title: 踏雪无痕d博客
name: agenthun
email: hun333@126.com
url: https://agenthun.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Henry Hu 2015
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/agenthun

# Postal address (add as many lines as necessary)
address:
  - line: East China Normal University
  - line: Minhang Campus 500 Dongchuan Rd
  - line: Shanghai, CHINA

# Credits content
credits: 'The blog is created by <a href="http://ironsummitmedia.github.io/startbootstrap-freelancer">Freelancer</a>.'

# Build settings
markdown: kramdown
permalink: pretty
